# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ragtune < Formula
  desc "EXPLAIN ANALYZE for RAG retrieval — inspect, explain, benchmark, and tune your RAG retrieval layer"
  homepage "https://github.com/metawake/ragtune"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/metawake/ragtune/releases/download/v0.1.0/ragtune_0.1.0_darwin_amd64.tar.gz"
      sha256 "3653e743b2cf7d3efa9ba523dcb9e71ca915813933314e44a6e3f6013f4c5913"

      def install
        bin.install "ragtune"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/metawake/ragtune/releases/download/v0.1.0/ragtune_0.1.0_darwin_arm64.tar.gz"
      sha256 "57b5bcafd65976e81f0d1b352db80da122937f826683286d3c9cbccce58f3cab"

      def install
        bin.install "ragtune"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/metawake/ragtune/releases/download/v0.1.0/ragtune_0.1.0_linux_amd64.tar.gz"
      sha256 "1237062259a39797588bcfdd86c106586235c746f195cef15332c67b1b88410b"
      def install
        bin.install "ragtune"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metawake/ragtune/releases/download/v0.1.0/ragtune_0.1.0_linux_arm64.tar.gz"
      sha256 "cf65b9776e36ad36a2920e7910214e3de654575644fe14efd1f81ca1d870ed9c"
      def install
        bin.install "ragtune"
      end
    end
  end

  test do
    system "#{bin}/ragtune", "--version"
  end
end
