# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ragtune < Formula
  desc "EXPLAIN ANALYZE for RAG retrieval — inspect, explain, benchmark, and tune your RAG retrieval layer"
  homepage "https://github.com/metawake/ragtune"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/metawake/ragtune/releases/download/v0.1.1/ragtune_0.1.1_darwin_amd64.tar.gz"
      sha256 "cbdff72eb2fc51ee07bb349c209fd0b14bc7490e768b93695ebd25af347db1c5"

      def install
        bin.install "ragtune"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/metawake/ragtune/releases/download/v0.1.1/ragtune_0.1.1_darwin_arm64.tar.gz"
      sha256 "c7481988c22d4efcbf14bff21f3324ddad7af5411ddab573721719855ffb3af1"

      def install
        bin.install "ragtune"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/metawake/ragtune/releases/download/v0.1.1/ragtune_0.1.1_linux_amd64.tar.gz"
      sha256 "48a5ec3deb7b17f825bbfab918b9c60e2032b3c4d7445f3fa17189549ef4c461"
      def install
        bin.install "ragtune"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metawake/ragtune/releases/download/v0.1.1/ragtune_0.1.1_linux_arm64.tar.gz"
      sha256 "cc8c3810b1f4d1f04428cf3db22cf3f2f569cccdb39ae30c9f1a2d80d1cf2c0e"
      def install
        bin.install "ragtune"
      end
    end
  end

  test do
    system "#{bin}/ragtune", "--version"
  end
end
