# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ragtune < Formula
  desc "EXPLAIN ANALYZE for RAG retrieval — inspect, explain, benchmark, and tune your RAG retrieval layer"
  homepage "https://github.com/metawake/ragtune"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/metawake/ragtune/releases/download/v0.2.0/ragtune_0.2.0_darwin_amd64.tar.gz"
      sha256 "901f3e1c172b71c59d7da5da47a82a246164d2f2a07723a9e27b277a30e9a6ee"

      def install
        bin.install "ragtune"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/metawake/ragtune/releases/download/v0.2.0/ragtune_0.2.0_darwin_arm64.tar.gz"
      sha256 "0a4b2899559ba8c6689fa1047896879423c9577b04e2408a240a7dbbf1fa31ce"

      def install
        bin.install "ragtune"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/metawake/ragtune/releases/download/v0.2.0/ragtune_0.2.0_linux_amd64.tar.gz"
      sha256 "df56622d605a36f66d8efafa4b475cd5c8812023c5943b9682389c5b79c3b267"
      def install
        bin.install "ragtune"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/metawake/ragtune/releases/download/v0.2.0/ragtune_0.2.0_linux_arm64.tar.gz"
      sha256 "4f0e2fc77650366324b85e98769307552e52863b9d318b57d2fdbb6a8ecf8a2b"
      def install
        bin.install "ragtune"
      end
    end
  end

  test do
    system "#{bin}/ragtune", "--version"
  end
end
